use std::os::raw::c_int;

#[repr(C)]
#[derive(Copy, Clone)]
pub(crate) struct NervaCudaHfDecodeChainLayer {
    pub(crate) rms_attn_weight: *const u16,
    pub(crate) rms_mlp_weight: *const u16,
    pub(crate) w_q: *const u16,
    pub(crate) w_q_gate: *const u16,
    pub(crate) w_k: *const u16,
    pub(crate) q_norm_weight: *const u16,
    pub(crate) k_norm_weight: *const u16,
    pub(crate) w_v: *const u16,
    pub(crate) w_o: *const u16,
    pub(crate) q_bias: *const u16,
    pub(crate) k_bias: *const u16,
    pub(crate) v_bias: *const u16,
    pub(crate) o_bias: *const u16,
    pub(crate) w_gate: *const u16,
    pub(crate) w_up: *const u16,
    pub(crate) w_down: *const u16,
    pub(crate) w_router: *const u16,
    pub(crate) w_expert_gate_up: *const u16,
    pub(crate) w_expert_down: *const u16,
    pub(crate) w_shared_expert_gate: *const u16,
    pub(crate) w_shared_expert_up: *const u16,
    pub(crate) w_shared_expert_down: *const u16,
    pub(crate) w_shared_expert_router: *const u16,
    pub(crate) linear_key_heads: u32,
    pub(crate) linear_value_heads: u32,
    pub(crate) linear_key_head_dim: u32,
    pub(crate) linear_value_head_dim: u32,
    pub(crate) linear_conv_kernel: u32,
    pub(crate) w_linear_conv: *const u16,
    pub(crate) w_linear_qkv: *const u16,
    pub(crate) w_linear_z: *const u16,
    pub(crate) w_linear_b: *const u16,
    pub(crate) w_linear_a: *const u16,
    pub(crate) w_linear_dt_bias: *const u16,
    pub(crate) w_linear_a_log: *const f32,
    pub(crate) w_linear_norm: *const u16,
    pub(crate) w_linear_out: *const u16,
    pub(crate) mlp_kind: u32,
    pub(crate) moe_intermediate: u32,
    pub(crate) shared_expert_intermediate: u32,
    pub(crate) num_experts: u32,
    pub(crate) experts_per_token: u32,
    pub(crate) norm_topk_prob: u32,
    pub(crate) attention_kind: u32,
    pub(crate) deepseek_mode: u32,
    pub(crate) deepseek_flags: u32,
    pub(crate) deepseek_storage: u32,
    pub(crate) deepseek_hc_mult: u32,
    pub(crate) deepseek_hc_sinkhorn_iters: u32,
    pub(crate) deepseek_q_lora_rank: u32,
    pub(crate) deepseek_kv_lora_rank: u32,
    pub(crate) deepseek_o_lora_rank: u32,
    pub(crate) deepseek_o_groups: u32,
    pub(crate) deepseek_qk_nope_head_dim: u32,
    pub(crate) deepseek_qk_rope_head_dim: u32,
    pub(crate) deepseek_v_head_dim: u32,
    pub(crate) deepseek_compress_ratio: u32,
    pub(crate) deepseek_index_topk: u32,
    pub(crate) deepseek_index_n_heads: u32,
    pub(crate) deepseek_index_head_dim: u32,
    pub(crate) deepseek_router_num_groups: u32,
    pub(crate) deepseek_router_topk_groups: u32,
    pub(crate) deepseek_routed_scaling_factor: f32,
    pub(crate) deepseek_hc_eps: f32,
    pub(crate) deepseek_hc_post_alpha: f32,
    pub(crate) deepseek_rope_scaling_type: u32,
    pub(crate) deepseek_rope_original_max_position: u32,
    pub(crate) deepseek_rope_scaling_factor: f32,
    pub(crate) deepseek_rope_extrapolation_factor: f32,
    pub(crate) deepseek_rope_attn_factor: f32,
    pub(crate) deepseek_rope_beta_fast: f32,
    pub(crate) deepseek_rope_beta_slow: f32,
    pub(crate) deepseek_rope_mscale: f32,
    pub(crate) deepseek_rope_mscale_all_dim: f32,
    pub(crate) deepseek_compress_rope_theta: f32,
    pub(crate) deepseek_swiglu_limit: f32,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub(crate) struct NervaCudaHfDecodeChainRequest {
    pub(crate) dtype: u32,
    pub(crate) hidden: u32,
    pub(crate) heads: u32,
    pub(crate) kv_heads: u32,
    pub(crate) head_dim: u32,
    pub(crate) intermediate: u32,
    pub(crate) vocab_size: u32,
    pub(crate) layer_count: u32,
    pub(crate) position: u32,
    pub(crate) token_index: u64,
    pub(crate) rms_eps: f32,
    pub(crate) rope_theta: f32,
    pub(crate) input: *const u16,
    pub(crate) layers: *const NervaCudaHfDecodeChainLayer,
    pub(crate) final_norm_weight: *const u16,
    pub(crate) lm_head: *const u16,
}

#[repr(C)]
#[derive(Copy, Clone, Default)]
pub(crate) struct NervaCudaHfDecodeChainResult {
    pub(crate) status: i32,
    pub(crate) cuda_error: i32,
    pub(crate) device_count: i32,
    pub(crate) dtype: u32,
    pub(crate) hidden: u32,
    pub(crate) heads: u32,
    pub(crate) kv_heads: u32,
    pub(crate) head_dim: u32,
    pub(crate) intermediate: u32,
    pub(crate) vocab_size: u32,
    pub(crate) layer_count: u32,
    pub(crate) token_index: u64,
    pub(crate) token: u32,
    pub(crate) slot_version: u64,
    pub(crate) completion: u32,
    pub(crate) output_hash: u64,
    pub(crate) resident_weight_bytes: u64,
    pub(crate) device_arena_bytes: u64,
    pub(crate) pinned_host_bytes: u64,
    pub(crate) h2d_bytes: u64,
    pub(crate) d2h_bytes: u64,
    pub(crate) kernel_launches: u64,
    pub(crate) sync_calls: u64,
    pub(crate) hot_path_allocations: u64,
}

unsafe extern "C" {
    fn nerva_cuda_hf_decode_chain_u16(
        request: *const NervaCudaHfDecodeChainRequest,
        out: *mut NervaCudaHfDecodeChainResult,
    ) -> c_int;
}

pub(crate) fn run_hf_decode_chain_u16(
    request: &NervaCudaHfDecodeChainRequest,
    out: &mut NervaCudaHfDecodeChainResult,
) -> c_int {
    unsafe { nerva_cuda_hf_decode_chain_u16(request, out) }
}
