use nerva_core::types::id::token::TokenId;
use nerva_cuda::decode::hf_sequence::footprint::CudaHfDecodeSequenceFootprint;
use nerva_cuda::smoke::status::SmokeStatus;
use nerva_ledger::types::token::critical::TokenCriticalPathReport;
use nerva_ledger::types::token::ledger::TokenLedger;

use crate::engine::hf_cuda_decode::hash::tokens_json;
use crate::engine::hf_cuda_decode::summary_arrays::{
    critical_paths_json, json_opt_bool, json_opt_usize, json_string, status_json,
    token_ledgers_json,
};

#[derive(Clone, Debug, Default)]
pub struct HfCudaResidentWeightSummary {
    pub plan_steps: u64,
    pub plan_weight_bytes: u64,
    pub plan_descriptor_blocks: u64,
    pub plan_descriptor_hash: u64,
    pub hotset_promoted_blocks: u64,
    pub hotset_promoted_bytes: u64,
    pub hotset_kept_dram_blocks: u64,
    pub plan_gpu_resident_weight_bytes: u64,
    pub plan_gpu_staged_weight_bytes: u64,
    pub plan_fallback_weight_bytes: u64,
    pub plan_gpu_resident_steps: u64,
    pub plan_gpu_staged_steps: u64,
    pub plan_fallback_steps: u64,
    pub plan_block_version_dependencies: u64,
    pub run_steps: u64,
    pub run_gpu_resident_steps: u64,
    pub run_gpu_staged_steps: u64,
    pub run_fallback_steps: u64,
    pub run_block_version_dependencies: u64,
    pub cuda_contract_blocks: u64,
    pub cuda_contract_weight_bytes: u64,
    pub cuda_contract_descriptor_blocks: u64,
    pub cuda_contract_descriptor_hash: u64,
    pub cuda_contract_gpu_resident_h2d_bytes: u64,
    pub cuda_contract_gpu_staged_h2d_bytes: u64,
    pub cuda_contract_matched: bool,
    pub hot_path_allocations: u64,
}

impl HfCudaResidentWeightSummary {
    pub fn to_json(&self) -> String {
        format!(
            "{{\"plan_steps\":{},\"plan_weight_bytes\":{},\"plan_descriptor_blocks\":{},\"plan_descriptor_hash\":{},\"hotset_promoted_blocks\":{},\"hotset_promoted_bytes\":{},\"hotset_kept_dram_blocks\":{},\"plan_gpu_resident_weight_bytes\":{},\"plan_gpu_staged_weight_bytes\":{},\"plan_fallback_weight_bytes\":{},\"plan_gpu_resident_steps\":{},\"plan_gpu_staged_steps\":{},\"plan_fallback_steps\":{},\"plan_block_version_dependencies\":{},\"run_steps\":{},\"run_gpu_resident_steps\":{},\"run_gpu_staged_steps\":{},\"run_fallback_steps\":{},\"run_block_version_dependencies\":{},\"cuda_contract_blocks\":{},\"cuda_contract_weight_bytes\":{},\"cuda_contract_descriptor_blocks\":{},\"cuda_contract_descriptor_hash\":{},\"cuda_contract_gpu_resident_H2D_bytes\":{},\"cuda_contract_gpu_staged_H2D_bytes\":{},\"cuda_contract_matched\":{},\"hot_path_allocations\":{}}}",
            self.plan_steps,
            self.plan_weight_bytes,
            self.plan_descriptor_blocks,
            self.plan_descriptor_hash,
            self.hotset_promoted_blocks,
            self.hotset_promoted_bytes,
            self.hotset_kept_dram_blocks,
            self.plan_gpu_resident_weight_bytes,
            self.plan_gpu_staged_weight_bytes,
            self.plan_fallback_weight_bytes,
            self.plan_gpu_resident_steps,
            self.plan_gpu_staged_steps,
            self.plan_fallback_steps,
            self.plan_block_version_dependencies,
            self.run_steps,
            self.run_gpu_resident_steps,
            self.run_gpu_staged_steps,
            self.run_fallback_steps,
            self.run_block_version_dependencies,
            self.cuda_contract_blocks,
            self.cuda_contract_weight_bytes,
            self.cuda_contract_descriptor_blocks,
            self.cuda_contract_descriptor_hash,
            self.cuda_contract_gpu_resident_h2d_bytes,
            self.cuda_contract_gpu_staged_h2d_bytes,
            self.cuda_contract_matched,
            self.hot_path_allocations,
        )
    }
}

#[derive(Clone, Debug)]
pub struct HfCudaSeedDecodeSummary {
    pub status: SmokeStatus,
    pub steps_requested: usize,
    pub tokens: Vec<TokenId>,
    pub expected_tokens: Vec<TokenId>,
    pub reference_mode: &'static str,
    pub reference_verified: bool,
    pub parity: bool,
    pub ledger_count: u64,
    pub device_events: u64,
    pub copy_events: u64,
    pub hard_syncs: u64,
    pub soft_visibility_syncs: u64,
    pub execution_decisions: u64,
    pub resident_weight_bytes: u64,
    pub cuda_footprint: CudaHfDecodeSequenceFootprint,
    pub cuda_device_total_memory_bytes: Option<usize>,
    pub cuda_device_free_memory_bytes: Option<usize>,
    pub cuda_fits_device_free_memory: Option<bool>,
    pub resident_kv_bytes: u64,
    pub kv_tokens: u64,
    pub h2d_bytes: u64,
    pub d2h_bytes: u64,
    pub graph_replays: u64,
    pub graph_nodes: u64,
    pub graph_launches: u64,
    pub graph_captures: u64,
    pub graph_cache_hits: u64,
    pub graph_replay_events: u64,
    pub kernel_launches: u64,
    pub experimental_rt_selector_launches: u64,
    pub experimental_rt_sparse_attention_chunks: u32,
    pub experimental_rt_dense_attention_chunks: u32,
    pub experimental_rt_attention_chunks: u32,
    pub projection_ns: u64,
    pub qkv_projection_ns: u64,
    pub attention_output_projection_ns: u64,
    pub gate_up_projection_ns: u64,
    pub down_projection_ns: u64,
    pub lm_head_projection_ns: u64,
    pub attention_ns: u64,
    pub mlp_ns: u64,
    pub norm_ns: u64,
    pub sampling_ns: u64,
    pub sync_calls: u64,
    pub host_causality_edges: u64,
    pub hot_path_allocations: u64,
    pub deepseek_compressor_state_writes: u64,
    pub deepseek_compressed_kv_writes: u64,
    pub deepseek_indexer_state_writes: u64,
    pub deepseek_indexer_kv_writes: u64,
    pub deepseek_compressed_kv_attention_reads: u64,
    pub deepseek_compressed_kv_attention_slots_scanned: u64,
    pub deepseek_sparse_topk_selections: u64,
    pub deepseek_sparse_topk_slots_selected: u64,
    pub deepseek_sparse_topk_candidates_scored: u64,
    pub deepseek_sparse_topk_selection_hash: u64,
    pub deepseek_v3_grouped_router_selections: u64,
    pub deepseek_v4_bias_router_selections: u64,
    pub deepseek_v4_hash_router_selections: u64,
    pub deepseek_raw_attention_tokens_scanned: u64,
    pub deepseek_sparse_attention_output_hash: u64,
    pub output_hash: u64,
    pub expected_hash: u64,
    pub resident_weights: HfCudaResidentWeightSummary,
    pub critical_paths: Vec<TokenCriticalPathReport>,
    pub token_ledgers: Vec<TokenLedger>,
    pub error: Option<String>,
}

impl HfCudaSeedDecodeSummary {
    pub fn passed(&self) -> bool {
        self.status == SmokeStatus::Ok
            && self.reference_verified
            && self.parity
            && self.hot_path_allocations == 0
    }

    pub fn critical_paths_json(&self) -> String {
        critical_paths_json(&self.critical_paths)
    }

    pub fn token_ledgers_json(&self) -> String {
        token_ledgers_json(&self.token_ledgers)
    }

    pub fn to_json(&self) -> String {
        format!(
            "{{\"status\":\"{}\",\"steps_requested\":{},\"tokens\":{},\"expected_tokens\":{},\"reference_mode\":\"{}\",\"reference_verified\":{},\"parity\":{},\"ledger_count\":{},\"device_events\":{},\"copy_events\":{},\"hard_syncs\":{},\"soft_visibility_syncs\":{},\"execution_decisions\":{},\"resident_weight_bytes\":{},\"cuda_footprint\":{},\"cuda_device_total_memory_bytes\":{},\"cuda_device_free_memory_bytes\":{},\"cuda_fits_device_free_memory\":{},\"resident_kv_bytes\":{},\"kv_tokens\":{},\"H2D_bytes\":{},\"D2H_bytes\":{},\"graph_replays\":{},\"graph_nodes\":{},\"graph_launches\":{},\"graph_captures\":{},\"graph_cache_hits\":{},\"graph_replay_events\":{},\"kernel_launches\":{},\"experimental_rt_selector_launches\":{},\"experimental_rt_sparse_attention_chunks\":{},\"experimental_rt_dense_attention_chunks\":{},\"experimental_rt_attention_chunks\":{},\"projection_ns\":{},\"qkv_projection_ns\":{},\"attention_output_projection_ns\":{},\"gate_up_projection_ns\":{},\"down_projection_ns\":{},\"lm_head_projection_ns\":{},\"attention_ns\":{},\"mlp_ns\":{},\"norm_ns\":{},\"sampling_ns\":{},\"sync_calls\":{},\"host_causality_edges\":{},\"hot_path_allocations\":{},\"deepseek_compressor_state_writes\":{},\"deepseek_compressed_kv_writes\":{},\"deepseek_indexer_state_writes\":{},\"deepseek_indexer_kv_writes\":{},\"deepseek_compressed_kv_attention_reads\":{},\"deepseek_compressed_kv_attention_slots_scanned\":{},\"deepseek_sparse_topk_selections\":{},\"deepseek_sparse_topk_slots_selected\":{},\"deepseek_sparse_topk_candidates_scored\":{},\"deepseek_sparse_topk_selection_hash\":{},\"deepseek_v3_grouped_router_selections\":{},\"deepseek_v4_bias_router_selections\":{},\"deepseek_v4_hash_router_selections\":{},\"deepseek_raw_attention_tokens_scanned\":{},\"deepseek_sparse_attention_output_hash\":{},\"output_hash\":{},\"expected_hash\":{},\"resident_weight_plan\":{},\"critical_paths\":{},\"token_ledgers\":{},\"error\":{}}}",
            status_json(&self.status),
            self.steps_requested,
            tokens_json(&self.tokens),
            tokens_json(&self.expected_tokens),
            self.reference_mode,
            self.reference_verified,
            self.parity,
            self.ledger_count,
            self.device_events,
            self.copy_events,
            self.hard_syncs,
            self.soft_visibility_syncs,
            self.execution_decisions,
            self.resident_weight_bytes,
            self.cuda_footprint.to_json(),
            json_opt_usize(self.cuda_device_total_memory_bytes),
            json_opt_usize(self.cuda_device_free_memory_bytes),
            json_opt_bool(self.cuda_fits_device_free_memory),
            self.resident_kv_bytes,
            self.kv_tokens,
            self.h2d_bytes,
            self.d2h_bytes,
            self.graph_replays,
            self.graph_nodes,
            self.graph_launches,
            self.graph_captures,
            self.graph_cache_hits,
            self.graph_replay_events,
            self.kernel_launches,
            self.experimental_rt_selector_launches,
            self.experimental_rt_sparse_attention_chunks,
            self.experimental_rt_dense_attention_chunks,
            self.experimental_rt_attention_chunks,
            self.projection_ns,
            self.qkv_projection_ns,
            self.attention_output_projection_ns,
            self.gate_up_projection_ns,
            self.down_projection_ns,
            self.lm_head_projection_ns,
            self.attention_ns,
            self.mlp_ns,
            self.norm_ns,
            self.sampling_ns,
            self.sync_calls,
            self.host_causality_edges,
            self.hot_path_allocations,
            self.deepseek_compressor_state_writes,
            self.deepseek_compressed_kv_writes,
            self.deepseek_indexer_state_writes,
            self.deepseek_indexer_kv_writes,
            self.deepseek_compressed_kv_attention_reads,
            self.deepseek_compressed_kv_attention_slots_scanned,
            self.deepseek_sparse_topk_selections,
            self.deepseek_sparse_topk_slots_selected,
            self.deepseek_sparse_topk_candidates_scored,
            self.deepseek_sparse_topk_selection_hash,
            self.deepseek_v3_grouped_router_selections,
            self.deepseek_v4_bias_router_selections,
            self.deepseek_v4_hash_router_selections,
            self.deepseek_raw_attention_tokens_scanned,
            self.deepseek_sparse_attention_output_hash,
            self.output_hash,
            self.expected_hash,
            self.resident_weights.to_json(),
            critical_paths_json(&self.critical_paths),
            token_ledgers_json(&self.token_ledgers),
            json_string(self.error.as_deref()),
        )
    }
}
