use crate::decode::hf_sequence::footprint::CudaHfDecodeSequenceFootprint;
use crate::decode::hf_sequence::summary::CudaHfDecodeSequenceSummary;
use crate::smoke::status::SmokeStatus;

pub(crate) fn empty_summary(
    status: SmokeStatus,
    dtype: u32,
    hidden: usize,
    vocab_size: usize,
    steps: usize,
    seed_token: u32,
    error: String,
) -> CudaHfDecodeSequenceSummary {
    CudaHfDecodeSequenceSummary {
        status,
        dtype,
        hidden: hidden as u32,
        heads: 0,
        kv_heads: 0,
        head_dim: 0,
        intermediate: 0,
        vocab_size: vocab_size as u32,
        layer_count: 0,
        steps: steps as u32,
        seed_token,
        tokens: Vec::new(),
        observed_token_hash: 0,
        planned_footprint: CudaHfDecodeSequenceFootprint::default(),
        device_total_memory_bytes: None,
        device_free_memory_bytes: None,
        fits_device_free_memory: None,
        resident_weight_bytes: 0,
        planned_weight_blocks: 0,
        planned_gpu_resident_blocks: 0,
        planned_gpu_staged_blocks: 0,
        planned_weight_bytes: 0,
        planned_gpu_resident_weight_bytes: 0,
        planned_gpu_staged_weight_bytes: 0,
        descriptor_gpu_resident_h2d_bytes: 0,
        descriptor_gpu_staged_h2d_bytes: 0,
        planned_weight_descriptor_count: 0,
        planned_weight_descriptor_hash: 0,
        resident_kv_bytes: 0,
        kv_tokens: 0,
        device_arena_bytes: 0,
        pinned_host_bytes: 0,
        h2d_bytes: 0,
        d2h_bytes: 0,
        graph_replays: 0,
        graph_nodes: 0,
        graph_launches: 0,
        graph_captures: 0,
        graph_cache_hits: 0,
        kernel_launches: 0,
        experimental_rt_selector_launches: 0,
        experimental_rt_sparse_attention_active: false,
        experimental_rt_dense_attention_chunks: 0,
        experimental_rt_attention_chunks: 0,
        device_elapsed_ns: 0,
        projection_ns: 0,
        qkv_projection_ns: 0,
        attention_output_projection_ns: 0,
        gate_up_projection_ns: 0,
        down_projection_ns: 0,
        lm_head_projection_ns: 0,
        attention_ns: 0,
        mlp_ns: 0,
        norm_ns: 0,
        sampling_ns: 0,
        sync_calls: 0,
        host_causality_edges: 0,
        hot_path_allocations: 0,
        deepseek_compressor_state_writes: 0,
        deepseek_compressed_kv_writes: 0,
        deepseek_indexer_state_writes: 0,
        deepseek_indexer_kv_writes: 0,
        deepseek_compressed_kv_attention_reads: 0,
        deepseek_compressed_kv_attention_slots_scanned: 0,
        error: Some(error),
    }
}
