use crate::experimental_rt::summary_json::summary_to_json;
use crate::experimental_rt::summary_status::summary_passed;
use crate::smoke::status::SmokeStatus;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CudaExperimentalRtCandidateBenchSummary {
    pub status: SmokeStatus,
    pub backend: String,
    pub reason: String,
    pub pages: u32,
    pub page_tokens: u32,
    pub dims: u32,
    pub query_count: u32,
    pub candidates_per_query: u32,
    pub iterations: u32,
    pub warmup_iterations: u32,
    pub compute_capability_major: Option<i32>,
    pub compute_capability_minor: Option<i32>,
    pub rt_core_capable: bool,
    pub real_rt_backend_available: bool,
    pub rt_headers_available: bool,
    pub optix_headers_available: bool,
    pub vulkan_headers_available: bool,
    pub vulkan_shader_compiler_available: bool,
    pub vulkan_loader_available: bool,
    pub vulkan_rt_extensions_available: bool,
    pub vulkan_physical_devices: u32,
    pub descriptor_bytes: u64,
    pub query_bytes: u64,
    pub kv_cache_bytes: u64,
    pub candidate_id_bytes: u64,
    pub output_bytes: u64,
    pub dense_selector_total_ns: u64,
    pub dense_selector_avg_ns: u64,
    pub software_selector_total_ns: u64,
    pub software_selector_avg_ns: u64,
    pub candidate_selector_total_ns: u64,
    pub candidate_selector_avg_ns: u64,
    pub rerank_total_ns: u64,
    pub rerank_avg_ns: u64,
    pub selector_plus_rerank_avg_ns: u64,
    pub dense_vs_selector_speedup_x1000: u64,
    pub dense_vs_selector_plus_rerank_speedup_x1000: u64,
    pub candidate_fraction_ppm: u64,
    pub candidate_parity_checked: bool,
    pub candidate_parity_mismatches: u64,
    pub candidate_parity_first_mismatch_index: u64,
    pub candidate_parity_first_expected: u64,
    pub candidate_parity_first_actual: u64,
    pub candidate_query_hashes_distinct: u64,
    pub candidate_query_hash_repeats: u64,
    pub local_window_tokens: u64,
    pub local_attention_total_ns: u64,
    pub local_attention_avg_ns: u64,
    pub kv_page_access_total_ns: u64,
    pub kv_page_access_avg_ns: u64,
    pub far_sparse_attention_total_ns: u64,
    pub far_sparse_attention_avg_ns: u64,
    pub softmax_merge_total_ns: u64,
    pub softmax_merge_avg_ns: u64,
    pub dense_full_attention_total_ns: u64,
    pub dense_full_attention_avg_ns: u64,
    pub attention_mass_recall_min_ppm: u64,
    pub attention_mass_recall_avg_ppm: u64,
    pub page_level_attention_mass_recall_min_ppm: u64,
    pub page_level_attention_mass_recall_avg_ppm: u64,
    pub far_oracle_topk_tokens: u64,
    pub far_oracle_topk_token_recall_min_ppm: u64,
    pub far_oracle_topk_token_recall_avg_ppm: u64,
    pub page_level_far_oracle_topk_token_recall_min_ppm: u64,
    pub page_level_far_oracle_topk_token_recall_avg_ppm: u64,
    pub far_oracle_topk_importance_scatter_min_pages: u64,
    pub far_oracle_topk_importance_scatter_avg_pages_x1000: u64,
    pub far_oracle_topk_importance_scatter_max_pages: u64,
    pub fine_token_projected_topk_tokens: u64,
    pub fine_token_projected_candidate_tokens: u64,
    pub fine_token_projected_token_recall_min_ppm: u64,
    pub fine_token_projected_token_recall_avg_ppm: u64,
    pub fine_token_learned_projected_topk_tokens: u64,
    pub fine_token_learned_projected_candidate_tokens: u64,
    pub fine_token_learned_projected_token_recall_min_ppm: u64,
    pub fine_token_learned_projected_token_recall_avg_ppm: u64,
    pub norm_stress_topk_tokens: u64,
    pub norm_stress_no_augmentation_token_recall_min_ppm: u64,
    pub norm_stress_no_augmentation_token_recall_avg_ppm: u64,
    pub norm_stress_synthetic_norm_augmented_token_recall_min_ppm: u64,
    pub norm_stress_synthetic_norm_augmented_token_recall_avg_ppm: u64,
    pub dense_selector_attention_stage_avg_ns: u64,
    pub rt_selector_attention_stage_avg_ns: u64,
    pub rt_selector_overlapped_attention_stage_avg_ns: u64,
    pub dense_vs_rt_attention_stage_speedup_x1000: u64,
    pub dense_vs_rt_overlapped_attention_stage_speedup_x1000: u64,
    pub dense_full_vs_rt_attention_stage_speedup_x1000: u64,
    pub dense_full_vs_rt_overlapped_attention_stage_speedup_x1000: u64,
    pub selected_hash: u64,
    pub kernel_launches: u64,
    pub sync_calls: u64,
    pub device_allocations: u64,
    pub device_frees: u64,
    pub device_arena_bytes: u64,
    pub hot_path_allocations: u64,
    pub error: Option<String>,
}

impl CudaExperimentalRtCandidateBenchSummary {
    pub fn passed(&self) -> bool {
        summary_passed(self)
    }

    pub fn to_json(&self) -> String {
        summary_to_json(self)
    }
}
