use crate::experimental_rt::summary::CudaExperimentalRtCandidateBenchSummary;
use crate::smoke::status::SmokeStatus;

impl CudaExperimentalRtCandidateBenchSummary {
    pub fn failed(
        pages: u32,
        page_tokens: u32,
        dims: u32,
        query_count: u32,
        candidates_per_query: u32,
        iterations: u32,
        warmup_iterations: u32,
        reason: String,
    ) -> Self {
        Self {
            status: SmokeStatus::Failed,
            backend: "unavailable".to_string(),
            reason: "experimental RT candidate selector bench did not run".to_string(),
            pages,
            page_tokens,
            dims,
            query_count,
            candidates_per_query,
            iterations,
            warmup_iterations,
            compute_capability_major: None,
            compute_capability_minor: None,
            rt_core_capable: false,
            real_rt_backend_available: false,
            rt_headers_available: false,
            optix_headers_available: false,
            vulkan_headers_available: false,
            vulkan_shader_compiler_available: false,
            vulkan_loader_available: false,
            vulkan_rt_extensions_available: false,
            vulkan_physical_devices: 0,
            descriptor_bytes: 0,
            query_bytes: 0,
            kv_cache_bytes: 0,
            candidate_id_bytes: 0,
            output_bytes: 0,
            dense_selector_total_ns: 0,
            dense_selector_avg_ns: 0,
            software_selector_total_ns: 0,
            software_selector_avg_ns: 0,
            candidate_selector_total_ns: 0,
            candidate_selector_avg_ns: 0,
            rerank_total_ns: 0,
            rerank_avg_ns: 0,
            selector_plus_rerank_avg_ns: 0,
            dense_vs_selector_speedup_x1000: 0,
            dense_vs_selector_plus_rerank_speedup_x1000: 0,
            candidate_fraction_ppm: 0,
            candidate_parity_checked: false,
            candidate_parity_mismatches: 0,
            candidate_parity_first_mismatch_index: 0,
            candidate_parity_first_expected: 0,
            candidate_parity_first_actual: 0,
            candidate_query_hashes_distinct: 0,
            candidate_query_hash_repeats: 0,
            local_window_tokens: 0,
            local_attention_total_ns: 0,
            local_attention_avg_ns: 0,
            kv_page_access_total_ns: 0,
            kv_page_access_avg_ns: 0,
            far_sparse_attention_total_ns: 0,
            far_sparse_attention_avg_ns: 0,
            softmax_merge_total_ns: 0,
            softmax_merge_avg_ns: 0,
            dense_full_attention_total_ns: 0,
            dense_full_attention_avg_ns: 0,
            attention_mass_recall_min_ppm: 0,
            attention_mass_recall_avg_ppm: 0,
            page_level_attention_mass_recall_min_ppm: 0,
            page_level_attention_mass_recall_avg_ppm: 0,
            far_oracle_topk_tokens: 0,
            far_oracle_topk_token_recall_min_ppm: 0,
            far_oracle_topk_token_recall_avg_ppm: 0,
            page_level_far_oracle_topk_token_recall_min_ppm: 0,
            page_level_far_oracle_topk_token_recall_avg_ppm: 0,
            far_oracle_topk_importance_scatter_min_pages: 0,
            far_oracle_topk_importance_scatter_avg_pages_x1000: 0,
            far_oracle_topk_importance_scatter_max_pages: 0,
            fine_token_projected_topk_tokens: 0,
            fine_token_projected_candidate_tokens: 0,
            fine_token_projected_token_recall_min_ppm: 0,
            fine_token_projected_token_recall_avg_ppm: 0,
            fine_token_learned_projected_topk_tokens: 0,
            fine_token_learned_projected_candidate_tokens: 0,
            fine_token_learned_projected_token_recall_min_ppm: 0,
            fine_token_learned_projected_token_recall_avg_ppm: 0,
            norm_stress_topk_tokens: 0,
            norm_stress_no_augmentation_token_recall_min_ppm: 0,
            norm_stress_no_augmentation_token_recall_avg_ppm: 0,
            norm_stress_synthetic_norm_augmented_token_recall_min_ppm: 0,
            norm_stress_synthetic_norm_augmented_token_recall_avg_ppm: 0,
            dense_selector_attention_stage_avg_ns: 0,
            rt_selector_attention_stage_avg_ns: 0,
            rt_selector_overlapped_attention_stage_avg_ns: 0,
            dense_vs_rt_attention_stage_speedup_x1000: 0,
            dense_vs_rt_overlapped_attention_stage_speedup_x1000: 0,
            dense_full_vs_rt_attention_stage_speedup_x1000: 0,
            dense_full_vs_rt_overlapped_attention_stage_speedup_x1000: 0,
            selected_hash: 0,
            kernel_launches: 0,
            sync_calls: 0,
            device_allocations: 0,
            device_frees: 0,
            device_arena_bytes: 0,
            hot_path_allocations: 0,
            error: Some(reason),
        }
    }

    pub fn unavailable(
        pages: u32,
        page_tokens: u32,
        dims: u32,
        query_count: u32,
        candidates_per_query: u32,
        iterations: u32,
        warmup_iterations: u32,
        reason: String,
    ) -> Self {
        Self {
            status: SmokeStatus::Unavailable,
            ..Self::failed(
                pages,
                page_tokens,
                dims,
                query_count,
                candidates_per_query,
                iterations,
                warmup_iterations,
                reason,
            )
        }
    }
}
