use crate::experimental_rt::summary::CudaExperimentalRtCandidateBenchSummary;
use crate::experimental_rt::summary_bytes::synthetic_kv_byte_estimates;
use crate::json::{escape_json, json_opt_i32, json_opt_str};
use crate::smoke::status::SmokeStatus;

pub(crate) fn summary_to_json(summary: &CudaExperimentalRtCandidateBenchSummary) -> String {
    let status = match summary.status {
        SmokeStatus::Ok => "ok",
        SmokeStatus::Unavailable => "unavailable",
        SmokeStatus::Failed => "failed",
    };
    let bytes = synthetic_kv_byte_estimates(summary);
    format!(
        "{{\"status\":\"{}\",\"backend\":\"{}\",\"reason\":\"{}\",\"pages\":{},\"page_tokens\":{},\"dims\":{},\"query_count\":{},\"candidates_per_query\":{},\"iterations\":{},\"warmup_iterations\":{},\"compute_capability_major\":{},\"compute_capability_minor\":{},\"rt_core_capable\":{},\"real_rt_backend_available\":{},\"rt_headers_available\":{},\"optix_headers_available\":{},\"vulkan_headers_available\":{},\"vulkan_shader_compiler_available\":{},\"vulkan_loader_available\":{},\"vulkan_rt_extensions_available\":{},\"vulkan_physical_devices\":{},\"descriptor_bytes\":{},\"query_bytes\":{},\"kv_cache_bytes\":{},\"synthetic_kv_bytes_per_token\":{},\"synthetic_dense_full_kv_bytes_per_query\":{},\"synthetic_local_window_kv_bytes_per_query\":{},\"synthetic_candidate_page_kv_bytes_per_query\":{},\"synthetic_estimated_rt_attention_kv_bytes_per_query\":{},\"synthetic_estimated_rt_vs_dense_kv_fraction_ppm\":{},\"candidate_id_bytes\":{},\"output_bytes\":{},\"dense_selector_total_ns\":{},\"dense_selector_avg_ns\":{},\"candidate_selector_total_ns\":{},\"candidate_selector_avg_ns\":{},\"software_selector_total_ns\":{},\"software_selector_avg_ns\":{},\"rerank_total_ns\":{},\"rerank_avg_ns\":{},\"selector_plus_rerank_avg_ns\":{},\"dense_vs_selector_speedup_x1000\":{},\"dense_vs_selector_plus_rerank_speedup_x1000\":{},\"candidate_fraction_ppm\":{},\"candidate_parity_checked\":{},\"candidate_parity_mismatches\":{},\"candidate_parity_first_mismatch_index\":{},\"candidate_parity_first_expected\":{},\"candidate_parity_first_actual\":{},\"candidate_query_hashes_distinct\":{},\"candidate_query_hash_repeats\":{},\"local_window_tokens\":{},\"local_attention_total_ns\":{},\"local_attention_avg_ns\":{},\"kv_page_access_total_ns\":{},\"kv_page_access_avg_ns\":{},\"far_sparse_attention_total_ns\":{},\"far_sparse_attention_avg_ns\":{},\"softmax_merge_total_ns\":{},\"softmax_merge_avg_ns\":{},\"dense_full_attention_total_ns\":{},\"dense_full_attention_avg_ns\":{},\"attention_mass_recall_min_ppm\":{},\"attention_mass_recall_avg_ppm\":{},\"page_level_attention_mass_recall_min_ppm\":{},\"page_level_attention_mass_recall_avg_ppm\":{},\"far_oracle_topk_tokens\":{},\"far_oracle_topk_token_recall_min_ppm\":{},\"far_oracle_topk_token_recall_avg_ppm\":{},\"page_level_far_oracle_topk_token_recall_min_ppm\":{},\"page_level_far_oracle_topk_token_recall_avg_ppm\":{},\"far_oracle_topk_importance_scatter_min_pages\":{},\"far_oracle_topk_importance_scatter_avg_pages_x1000\":{},\"far_oracle_topk_importance_scatter_max_pages\":{},\"dense_selector_attention_stage_avg_ns\":{},\"rt_selector_attention_stage_avg_ns\":{},\"rt_selector_overlapped_attention_stage_avg_ns\":{},\"dense_vs_rt_attention_stage_speedup_x1000\":{},\"dense_vs_rt_overlapped_attention_stage_speedup_x1000\":{},\"dense_full_vs_rt_attention_stage_speedup_x1000\":{},\"dense_full_vs_rt_overlapped_attention_stage_speedup_x1000\":{},\"selected_hash\":{},\"kernel_launches\":{},\"sync_calls\":{},\"device_allocations\":{},\"device_frees\":{},\"device_arena_bytes\":{},\"hot_path_allocations\":{},\"error\":{}}}",
        status,
        escape_json(&summary.backend),
        escape_json(&summary.reason),
        summary.pages,
        summary.page_tokens,
        summary.dims,
        summary.query_count,
        summary.candidates_per_query,
        summary.iterations,
        summary.warmup_iterations,
        json_opt_i32(summary.compute_capability_major),
        json_opt_i32(summary.compute_capability_minor),
        summary.rt_core_capable,
        summary.real_rt_backend_available,
        summary.rt_headers_available,
        summary.optix_headers_available,
        summary.vulkan_headers_available,
        summary.vulkan_shader_compiler_available,
        summary.vulkan_loader_available,
        summary.vulkan_rt_extensions_available,
        summary.vulkan_physical_devices,
        summary.descriptor_bytes,
        summary.query_bytes,
        summary.kv_cache_bytes,
        bytes.kv_bytes_per_token,
        bytes.dense_full_kv_bytes_per_query,
        bytes.local_window_kv_bytes_per_query,
        bytes.candidate_page_kv_bytes_per_query,
        bytes.estimated_rt_attention_kv_bytes_per_query,
        bytes.estimated_rt_vs_dense_kv_fraction_ppm,
        summary.candidate_id_bytes,
        summary.output_bytes,
        summary.dense_selector_total_ns,
        summary.dense_selector_avg_ns,
        summary.candidate_selector_total_ns,
        summary.candidate_selector_avg_ns,
        summary.software_selector_total_ns,
        summary.software_selector_avg_ns,
        summary.rerank_total_ns,
        summary.rerank_avg_ns,
        summary.selector_plus_rerank_avg_ns,
        summary.dense_vs_selector_speedup_x1000,
        summary.dense_vs_selector_plus_rerank_speedup_x1000,
        summary.candidate_fraction_ppm,
        summary.candidate_parity_checked,
        summary.candidate_parity_mismatches,
        summary.candidate_parity_first_mismatch_index,
        summary.candidate_parity_first_expected,
        summary.candidate_parity_first_actual,
        summary.candidate_query_hashes_distinct,
        summary.candidate_query_hash_repeats,
        summary.local_window_tokens,
        summary.local_attention_total_ns,
        summary.local_attention_avg_ns,
        summary.kv_page_access_total_ns,
        summary.kv_page_access_avg_ns,
        summary.far_sparse_attention_total_ns,
        summary.far_sparse_attention_avg_ns,
        summary.softmax_merge_total_ns,
        summary.softmax_merge_avg_ns,
        summary.dense_full_attention_total_ns,
        summary.dense_full_attention_avg_ns,
        summary.attention_mass_recall_min_ppm,
        summary.attention_mass_recall_avg_ppm,
        summary.page_level_attention_mass_recall_min_ppm,
        summary.page_level_attention_mass_recall_avg_ppm,
        summary.far_oracle_topk_tokens,
        summary.far_oracle_topk_token_recall_min_ppm,
        summary.far_oracle_topk_token_recall_avg_ppm,
        summary.page_level_far_oracle_topk_token_recall_min_ppm,
        summary.page_level_far_oracle_topk_token_recall_avg_ppm,
        summary.far_oracle_topk_importance_scatter_min_pages,
        summary.far_oracle_topk_importance_scatter_avg_pages_x1000,
        summary.far_oracle_topk_importance_scatter_max_pages,
        summary.dense_selector_attention_stage_avg_ns,
        summary.rt_selector_attention_stage_avg_ns,
        summary.rt_selector_overlapped_attention_stage_avg_ns,
        summary.dense_vs_rt_attention_stage_speedup_x1000,
        summary.dense_vs_rt_overlapped_attention_stage_speedup_x1000,
        summary.dense_full_vs_rt_attention_stage_speedup_x1000,
        summary.dense_full_vs_rt_overlapped_attention_stage_speedup_x1000,
        summary.selected_hash,
        summary.kernel_launches,
        summary.sync_calls,
        summary.device_allocations,
        summary.device_frees,
        summary.device_arena_bytes,
        summary.hot_path_allocations,
        json_opt_str(summary.error.as_deref()),
    )
}
