const COMMANDS: &[&str] = &[
    "smoke",
    "cuda-backend [device_bytes] [pinned_bytes]",
    "cuda-graph [steps] [ring_capacity] [seed_token]",
    "cuda-block",
    "cuda-loaded-block",
    "cuda-attention",
    "cuda-sampler",
    "cuda-tiny-decode [steps] [ring_capacity] [seed_token]",
    "experimental-rt [context_tokens] [query_count] [candidates_per_query] [iterations] [page_tokens] [layer_count]",
    "experimental-rt-sweep [context_tokens] [query_count] [max_candidates_per_query] [iterations] [page_tokens] [min_candidates_per_query] [layer_count]",
    "experimental-rt-matrix [iterations] [page_tokens] [layer_count]",
    "capabilities",
    "backend-contract",
    "hot-path-guard",
    "security-isolation",
    "correctness",
    "production-invariants",
    "request-state",
    "request-scheduler",
    "topology",
    "synthetic [steps] [ring_capacity]",
    "ledger",
    "critical-path",
    "token-policy",
    "phase-handoff",
    "shared-queue",
    "transaction",
    "compute-near-data",
    "measurements",
    "measured-planner",
    "memory-loop",
    "projection-bench [rows] [cols] [dtype] [iterations] [warmup_iterations] [block_tokens]",
    "projection-batch-plan [ready_requests] [compatible_requests] [target_block_tokens] [min_block_tokens]",
    "projection-batch-exec-probe [ready_requests] [compatible_requests] [rows] [cols] [dtype] [iterations] [warmup_iterations] [target_block_tokens] [min_block_tokens]",
    "perf-baseline workload scope nerva_tps vllm_tps rvllm_tps nerva_p99_ms vllm_p99_ms rvllm_p99_ms",
    "external-baseline engine workload scope status evidence",
    "block",
    "precision",
    "safetensors-block",
    "model [steps]",
    "prompt-model [prompt] [steps]",
    "precision-model [steps]",
    "hf-decode checkpoint_dir [seed_token|ids:a,b,c|prompt_text] [steps]",
    "hf-cuda-decode checkpoint_dir [seed_token|ids:a,b,c|prompt_text] [steps]",
    "hf-cuda-decode-device-only checkpoint_dir [seed_token|ids:a,b,c|prompt_text] [steps]",
    "hf-cuda-decode-device-session checkpoint_dir [max_context] [steps] [token|ids:a,b,c]...",
    "hf-cuda-decode-device-session-loop checkpoint_dir [max_context] [chunk_steps] [chunks] [token|ids:a,b,c]",
    "hf-cuda-decode-device-session-stream checkpoint_dir [max_context] [chunk_steps] [chunks] [queue_capacity] [token|ids:a,b,c]",
    "hf-cuda-generate checkpoint_dir [max_context] [max_new_tokens] [queue_capacity] prompt_text|@prompt.txt [compute_capability]",
    "hf-cuda-shared-fork-batch [--experimental-rt] checkpoint_dir [request_count] [max_context] [max_new_tokens] [target_block_tokens] [min_block_tokens] prompt_text|@prompt.txt [compute_capability]",
    "hf-cuda-shared-fork-batch-compare [--experimental-rt] checkpoint_dir [request_count] [max_context] [max_new_tokens] [target_block_tokens] [min_block_tokens] prompt_text|@prompt.txt [compute_capability]",
    "vllm-parity vllm_tokens.json [steps]",
    "token-parity baseline_tokens.json candidate_tokens.json",
    "metadata [config.json]",
    "layout [config.json]",
    "manifest [config.json]",
    "manifest-coverage config.json model.safetensors.index.json",
    "deepseek-runtime-plan config.json",
    "deepseek-cuda-readiness [config.json]",
    "safetensors [config.json model.safetensors]",
    "safetensors-shards config.json model.safetensors.index.json checkpoint_dir",
    "resident-shards config.json model.safetensors.index.json checkpoint_dir [max_task_bytes]",
    "resident-weights [config.json]",
    "hotset [config.json] [vram_bytes] [max_promote_bytes]",
    "weight-exec [config.json] [vram_bytes] [max_promote_bytes] [max_steps] [compute_capability]",
    "attention",
    "warm",
    "contracts",
    "kv",
    "tiered-kv",
    "fabric-topology",
    "fabric-backends",
    "dpdk-udp",
    "kernel-udp",
    "kernel-udp-matrix",
    "tcp-control",
    "measured-transport",
    "transport-provenance",
    "transport",
    "transport-contract",
    "transport-matrix",
    "transport-registration",
    "transport-registration-lifecycle",
    "stage-pipeline",
    "multi-gpu",
    "acceptance",
    "artifact <probe> [probe args...]",
];

pub(crate) fn print_usage() {
    for (index, command) in COMMANDS.iter().enumerate() {
        let prefix = if index == 0 { "usage:" } else { "      " };
        eprintln!("{prefix} cargo run -p nerva-bench -- {command}");
    }
}
