const COMMANDS: &[&str] = &[
    "smoke",
    "cuda-backend [device_bytes] [pinned_bytes]",
    "cuda-graph [steps] [ring_capacity] [seed_token]",
    "cuda-block",
    "cuda-loaded-block",
    "cuda-attention",
    "cuda-sampler",
    "cuda-tiny-decode [steps] [ring_capacity] [seed_token]",
    "capabilities",
    "backend-contract",
    "hot-path-guard",
    "security-isolation",
    "correctness",
    "production-invariants",
    "request-state",
    "request-scheduler",
    "topology",
    "synthetic [steps] [ring_capacity]",
    "ledger",
    "critical-path",
    "token-policy",
    "phase-handoff",
    "shared-queue",
    "transaction",
    "compute-near-data",
    "measurements",
    "measured-planner",
    "memory-loop",
    "block",
    "precision",
    "safetensors-block",
    "model [steps]",
    "prompt-model [prompt] [steps]",
    "precision-model [steps]",
    "hf-decode checkpoint_dir [seed_token] [steps]",
    "vllm-parity vllm_tokens.json [steps]",
    "metadata [config.json]",
    "layout [config.json]",
    "manifest [config.json]",
    "safetensors [config.json model.safetensors]",
    "safetensors-shards config.json model.safetensors.index.json checkpoint_dir",
    "resident-shards config.json model.safetensors.index.json checkpoint_dir [max_task_bytes]",
    "resident-weights [config.json]",
    "hotset [config.json] [vram_bytes] [max_promote_bytes]",
    "weight-exec [config.json] [vram_bytes] [max_promote_bytes] [max_steps] [compute_capability]",
    "attention",
    "warm",
    "contracts",
    "kv",
    "tiered-kv",
    "fabric-topology",
    "fabric-backends",
    "dpdk-udp",
    "kernel-udp",
    "kernel-udp-matrix",
    "tcp-control",
    "measured-transport",
    "transport-provenance",
    "transport",
    "transport-contract",
    "transport-matrix",
    "transport-registration",
    "transport-registration-lifecycle",
    "stage-pipeline",
    "multi-gpu",
    "acceptance",
    "artifact <probe> [probe args...]",
];

pub(crate) fn print_usage() {
    for (index, command) in COMMANDS.iter().enumerate() {
        let prefix = if index == 0 { "usage:" } else { "      " };
        eprintln!("{prefix} cargo run -p nerva-bench -- {command}");
    }
}
