use crate::json::{json_opt_i32, json_opt_str};
use crate::projection::summary::CudaProjectionBenchSummary;
use crate::smoke::status::SmokeStatus;

pub(crate) fn summary_to_json(summary: &CudaProjectionBenchSummary) -> String {
    let status = match summary.status {
        SmokeStatus::Ok => "ok",
        SmokeStatus::Unavailable => "unavailable",
        SmokeStatus::Failed => "failed",
    };
    format!(
        "{{\"status\":\"{}\",\"dtype\":{},\"rows\":{},\"cols\":{},\"iterations\":{},\"warmup_iterations\":{},\"compute_capability_major\":{},\"compute_capability_minor\":{},\"matrix_bytes\":{},\"input_bytes\":{},\"output_bytes\":{},\"cublaslt_total_ns\":{},\"cublaslt_avg_ns\":{},\"cublaslt_default_total_ns\":{},\"cublaslt_default_avg_ns\":{},\"cublaslt_heuristic_count\":{},\"cublaslt_best_heuristic_index\":{},\"cublaslt_best_heuristic_total_ns\":{},\"cublaslt_best_heuristic_avg_ns\":{},\"custom_total_ns\":{},\"custom_avg_ns\":{},\"cublaslt_graph_total_ns\":{},\"cublaslt_graph_avg_ns\":{},\"cublaslt_default_graph_total_ns\":{},\"cublaslt_default_graph_avg_ns\":{},\"cublaslt_best_heuristic_graph_total_ns\":{},\"cublaslt_best_heuristic_graph_avg_ns\":{},\"custom_graph_total_ns\":{},\"custom_graph_avg_ns\":{},\"cublaslt_graph_nodes\":{},\"custom_graph_nodes\":{},\"graph_replays\":{},\"graph_captures\":{},\"selected_graph_strategy\":\"{}\",\"selected_graph_strategy_id\":{},\"cublaslt_effective_bandwidth_bps\":{},\"custom_effective_bandwidth_bps\":{},\"selected_strategy\":\"{}\",\"selected_strategy_id\":{},\"mismatch_count\":{},\"max_abs_diff\":{},\"kernel_launches\":{},\"sync_calls\":{},\"device_allocations\":{},\"device_frees\":{},\"device_arena_bytes\":{},\"hot_path_allocations\":{},\"error\":{}}}",
        status,
        summary.dtype,
        summary.rows,
        summary.cols,
        summary.iterations,
        summary.warmup_iterations,
        json_opt_i32(summary.compute_capability_major),
        json_opt_i32(summary.compute_capability_minor),
        summary.matrix_bytes,
        summary.input_bytes,
        summary.output_bytes,
        summary.cublaslt_total_ns,
        summary.cublaslt_avg_ns,
        summary.cublaslt_default_total_ns,
        summary.cublaslt_default_avg_ns,
        summary.cublaslt_heuristic_count,
        summary.cublaslt_best_heuristic_index,
        summary.cublaslt_best_heuristic_total_ns,
        summary.cublaslt_best_heuristic_avg_ns,
        summary.custom_total_ns,
        summary.custom_avg_ns,
        summary.cublaslt_graph_total_ns,
        summary.cublaslt_graph_avg_ns,
        summary.cublaslt_default_graph_total_ns,
        summary.cublaslt_default_graph_avg_ns,
        summary.cublaslt_best_heuristic_graph_total_ns,
        summary.cublaslt_best_heuristic_graph_avg_ns,
        summary.custom_graph_total_ns,
        summary.custom_graph_avg_ns,
        summary.cublaslt_graph_nodes,
        summary.custom_graph_nodes,
        summary.graph_replays,
        summary.graph_captures,
        summary.selected_graph_strategy_name(),
        summary.selected_graph_strategy,
        summary.cublaslt_effective_bandwidth_bps,
        summary.custom_effective_bandwidth_bps,
        summary.selected_strategy_name(),
        summary.selected_strategy,
        summary.mismatch_count,
        summary.max_abs_diff,
        summary.kernel_launches,
        summary.sync_calls,
        summary.device_allocations,
        summary.device_frees,
        summary.device_arena_bytes,
        summary.hot_path_allocations,
        json_opt_str(summary.error.as_deref()),
    )
}
