use nerva_core::types::dtype::DType;
use nerva_core::types::error::{NervaError, Result};
use nerva_core::types::memory::tier::MemoryTier;

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum WeightBlockRole {
    TokenEmbedding,
    AttentionNorm,
    QueryProjection,
    QueryNorm,
    QueryBias,
    KeyProjection,
    KeyNorm,
    KeyBias,
    ValueProjection,
    ValueBias,
    OutputProjection,
    OutputBias,
    DeepSeekQALoraProjection,
    DeepSeekQALoraScaleInv,
    DeepSeekQALoraNorm,
    DeepSeekQBProjection,
    DeepSeekQBScaleInv,
    DeepSeekKvAProjection,
    DeepSeekKvAScaleInv,
    DeepSeekKvANorm,
    DeepSeekKvBProjection,
    DeepSeekKvBScaleInv,
    DeepSeekOutputScaleInv,
    DeepSeekIndexerQueryProjection,
    DeepSeekIndexerQueryScaleInv,
    DeepSeekIndexerKeyProjection,
    DeepSeekIndexerKeyScaleInv,
    DeepSeekIndexerKeyNorm,
    DeepSeekIndexerKeyNormBias,
    DeepSeekIndexerWeightsProjection,
    DeepSeekV4HcHeadBase,
    DeepSeekV4HcHeadFn,
    DeepSeekV4HcHeadScale,
    DeepSeekV4HcAttnBase,
    DeepSeekV4HcAttnFn,
    DeepSeekV4HcAttnScale,
    DeepSeekV4HcFfnBase,
    DeepSeekV4HcFfnFn,
    DeepSeekV4HcFfnScale,
    DeepSeekV4AttentionSink,
    DeepSeekV4WqAProjection,
    DeepSeekV4WqAScale,
    DeepSeekV4WqBProjection,
    DeepSeekV4WqBScale,
    DeepSeekV4QNorm,
    DeepSeekV4WkvProjection,
    DeepSeekV4WkvScale,
    DeepSeekV4KvNorm,
    DeepSeekV4WoAProjection,
    DeepSeekV4WoAScale,
    DeepSeekV4WoBProjection,
    DeepSeekV4WoBScale,
    DeepSeekV4CompressorApe,
    DeepSeekV4CompressorWkvProjection,
    DeepSeekV4CompressorWkvScale,
    DeepSeekV4CompressorWgateProjection,
    DeepSeekV4CompressorWgateScale,
    DeepSeekV4CompressorNorm,
    DeepSeekV4IndexerWqBProjection,
    DeepSeekV4IndexerWqBScale,
    DeepSeekV4IndexerCompressorApe,
    DeepSeekV4IndexerCompressorWkvProjection,
    DeepSeekV4IndexerCompressorWkvScale,
    DeepSeekV4IndexerCompressorWgateProjection,
    DeepSeekV4IndexerCompressorWgateScale,
    DeepSeekV4IndexerCompressorNorm,
    DeepSeekV4IndexerWeightsProjection,
    DeepSeekV4IndexerWeightsScale,
    DeepSeekV4HashRouteTable,
    DeepSeekV4ExpertGateScale,
    DeepSeekV4ExpertUpScale,
    DeepSeekV4ExpertDownScale,
    DeepSeekV4SharedExpertGateScale,
    DeepSeekV4SharedExpertUpScale,
    DeepSeekV4SharedExpertDownScale,
    LinearConvProjection,
    LinearQkvProjection,
    LinearZProjection,
    LinearBProjection,
    LinearAProjection,
    LinearDtBias,
    LinearALog,
    LinearNorm,
    LinearOutputProjection,
    MlpNorm,
    GateProjection,
    UpProjection,
    DownProjection,
    GateScaleInv,
    UpScaleInv,
    DownScaleInv,
    RouterProjection,
    RouterCorrectionBias,
    ExpertGateProjection,
    ExpertUpProjection,
    ExpertGateUpProjection,
    ExpertDownProjection,
    ExpertGateScaleInv,
    ExpertUpScaleInv,
    ExpertDownScaleInv,
    SharedExpertGateProjection,
    SharedExpertUpProjection,
    SharedExpertDownProjection,
    SharedExpertGateScaleInv,
    SharedExpertUpScaleInv,
    SharedExpertDownScaleInv,
    SharedExpertRouterProjection,
    FinalNorm,
    LmHead,
}

impl WeightBlockRole {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::TokenEmbedding => "token_embedding",
            Self::AttentionNorm => "attention_norm",
            Self::QueryProjection => "q_proj",
            Self::QueryNorm => "q_norm",
            Self::QueryBias => "q_proj_bias",
            Self::KeyProjection => "k_proj",
            Self::KeyNorm => "k_norm",
            Self::KeyBias => "k_proj_bias",
            Self::ValueProjection => "v_proj",
            Self::ValueBias => "v_proj_bias",
            Self::OutputProjection => "o_proj",
            Self::OutputBias => "o_proj_bias",
            Self::DeepSeekQALoraProjection => "deepseek_q_a_proj",
            Self::DeepSeekQALoraScaleInv => "deepseek_q_a_proj_scale_inv",
            Self::DeepSeekQALoraNorm => "deepseek_q_a_layernorm",
            Self::DeepSeekQBProjection => "deepseek_q_b_proj",
            Self::DeepSeekQBScaleInv => "deepseek_q_b_proj_scale_inv",
            Self::DeepSeekKvAProjection => "deepseek_kv_a_proj_with_mqa",
            Self::DeepSeekKvAScaleInv => "deepseek_kv_a_proj_with_mqa_scale_inv",
            Self::DeepSeekKvANorm => "deepseek_kv_a_layernorm",
            Self::DeepSeekKvBProjection => "deepseek_kv_b_proj",
            Self::DeepSeekKvBScaleInv => "deepseek_kv_b_proj_scale_inv",
            Self::DeepSeekOutputScaleInv => "deepseek_o_proj_scale_inv",
            Self::DeepSeekIndexerQueryProjection => "deepseek_indexer_wq_b",
            Self::DeepSeekIndexerQueryScaleInv => "deepseek_indexer_wq_b_scale_inv",
            Self::DeepSeekIndexerKeyProjection => "deepseek_indexer_wk",
            Self::DeepSeekIndexerKeyScaleInv => "deepseek_indexer_wk_scale_inv",
            Self::DeepSeekIndexerKeyNorm => "deepseek_indexer_k_norm",
            Self::DeepSeekIndexerKeyNormBias => "deepseek_indexer_k_norm_bias",
            Self::DeepSeekIndexerWeightsProjection => "deepseek_indexer_weights_proj",
            Self::DeepSeekV4HcHeadBase => "deepseek_v4_hc_head_base",
            Self::DeepSeekV4HcHeadFn => "deepseek_v4_hc_head_fn",
            Self::DeepSeekV4HcHeadScale => "deepseek_v4_hc_head_scale",
            Self::DeepSeekV4HcAttnBase => "deepseek_v4_hc_attn_base",
            Self::DeepSeekV4HcAttnFn => "deepseek_v4_hc_attn_fn",
            Self::DeepSeekV4HcAttnScale => "deepseek_v4_hc_attn_scale",
            Self::DeepSeekV4HcFfnBase => "deepseek_v4_hc_ffn_base",
            Self::DeepSeekV4HcFfnFn => "deepseek_v4_hc_ffn_fn",
            Self::DeepSeekV4HcFfnScale => "deepseek_v4_hc_ffn_scale",
            Self::DeepSeekV4AttentionSink => "deepseek_v4_attn_sink",
            Self::DeepSeekV4WqAProjection => "deepseek_v4_wq_a",
            Self::DeepSeekV4WqAScale => "deepseek_v4_wq_a_scale",
            Self::DeepSeekV4WqBProjection => "deepseek_v4_wq_b",
            Self::DeepSeekV4WqBScale => "deepseek_v4_wq_b_scale",
            Self::DeepSeekV4QNorm => "deepseek_v4_q_norm",
            Self::DeepSeekV4WkvProjection => "deepseek_v4_wkv",
            Self::DeepSeekV4WkvScale => "deepseek_v4_wkv_scale",
            Self::DeepSeekV4KvNorm => "deepseek_v4_kv_norm",
            Self::DeepSeekV4WoAProjection => "deepseek_v4_wo_a",
            Self::DeepSeekV4WoAScale => "deepseek_v4_wo_a_scale",
            Self::DeepSeekV4WoBProjection => "deepseek_v4_wo_b",
            Self::DeepSeekV4WoBScale => "deepseek_v4_wo_b_scale",
            Self::DeepSeekV4CompressorApe => "deepseek_v4_compressor_ape",
            Self::DeepSeekV4CompressorWkvProjection => "deepseek_v4_compressor_wkv",
            Self::DeepSeekV4CompressorWkvScale => "deepseek_v4_compressor_wkv_scale",
            Self::DeepSeekV4CompressorWgateProjection => "deepseek_v4_compressor_wgate",
            Self::DeepSeekV4CompressorWgateScale => "deepseek_v4_compressor_wgate_scale",
            Self::DeepSeekV4CompressorNorm => "deepseek_v4_compressor_norm",
            Self::DeepSeekV4IndexerWqBProjection => "deepseek_v4_indexer_wq_b",
            Self::DeepSeekV4IndexerWqBScale => "deepseek_v4_indexer_wq_b_scale",
            Self::DeepSeekV4IndexerCompressorApe => "deepseek_v4_indexer_compressor_ape",
            Self::DeepSeekV4IndexerCompressorWkvProjection => "deepseek_v4_indexer_compressor_wkv",
            Self::DeepSeekV4IndexerCompressorWkvScale => "deepseek_v4_indexer_compressor_wkv_scale",
            Self::DeepSeekV4IndexerCompressorWgateProjection => {
                "deepseek_v4_indexer_compressor_wgate"
            }
            Self::DeepSeekV4IndexerCompressorWgateScale => {
                "deepseek_v4_indexer_compressor_wgate_scale"
            }
            Self::DeepSeekV4IndexerCompressorNorm => "deepseek_v4_indexer_compressor_norm",
            Self::DeepSeekV4IndexerWeightsProjection => "deepseek_v4_indexer_weights_proj",
            Self::DeepSeekV4IndexerWeightsScale => "deepseek_v4_indexer_weights_proj_scale",
            Self::DeepSeekV4HashRouteTable => "deepseek_v4_hash_route_table",
            Self::DeepSeekV4ExpertGateScale => "deepseek_v4_expert_w1_scale",
            Self::DeepSeekV4ExpertUpScale => "deepseek_v4_expert_w3_scale",
            Self::DeepSeekV4ExpertDownScale => "deepseek_v4_expert_w2_scale",
            Self::DeepSeekV4SharedExpertGateScale => "deepseek_v4_shared_expert_w1_scale",
            Self::DeepSeekV4SharedExpertUpScale => "deepseek_v4_shared_expert_w3_scale",
            Self::DeepSeekV4SharedExpertDownScale => "deepseek_v4_shared_expert_w2_scale",
            Self::LinearConvProjection => "linear_conv1d",
            Self::LinearQkvProjection => "linear_in_proj_qkv",
            Self::LinearZProjection => "linear_in_proj_z",
            Self::LinearBProjection => "linear_in_proj_b",
            Self::LinearAProjection => "linear_in_proj_a",
            Self::LinearDtBias => "linear_dt_bias",
            Self::LinearALog => "linear_a_log",
            Self::LinearNorm => "linear_norm",
            Self::LinearOutputProjection => "linear_out_proj",
            Self::MlpNorm => "mlp_norm",
            Self::GateProjection => "gate_proj",
            Self::UpProjection => "up_proj",
            Self::DownProjection => "down_proj",
            Self::GateScaleInv => "gate_proj_scale_inv",
            Self::UpScaleInv => "up_proj_scale_inv",
            Self::DownScaleInv => "down_proj_scale_inv",
            Self::RouterProjection => "router",
            Self::RouterCorrectionBias => "router_correction_bias",
            Self::ExpertGateProjection => "expert_gate_proj",
            Self::ExpertUpProjection => "expert_up_proj",
            Self::ExpertGateUpProjection => "expert_gate_up_proj",
            Self::ExpertDownProjection => "expert_down_proj",
            Self::ExpertGateScaleInv => "expert_gate_proj_scale_inv",
            Self::ExpertUpScaleInv => "expert_up_proj_scale_inv",
            Self::ExpertDownScaleInv => "expert_down_proj_scale_inv",
            Self::SharedExpertGateProjection => "shared_expert_gate_proj",
            Self::SharedExpertUpProjection => "shared_expert_up_proj",
            Self::SharedExpertDownProjection => "shared_expert_down_proj",
            Self::SharedExpertGateScaleInv => "shared_expert_gate_proj_scale_inv",
            Self::SharedExpertUpScaleInv => "shared_expert_up_proj_scale_inv",
            Self::SharedExpertDownScaleInv => "shared_expert_down_proj_scale_inv",
            Self::SharedExpertRouterProjection => "shared_expert_gate",
            Self::FinalNorm => "final_norm",
            Self::LmHead => "lm_head",
        }
    }
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct WeightBlockSpec {
    pub role: WeightBlockRole,
    pub layer: Option<u32>,
    pub rows: usize,
    pub cols: usize,
    pub depth: Option<usize>,
    pub elements: usize,
    pub bytes: usize,
    pub dtype: DType,
    pub tier: MemoryTier,
}

impl WeightBlockSpec {
    pub(crate) fn new(
        role: WeightBlockRole,
        layer: Option<u32>,
        rows: usize,
        cols: usize,
        dtype: DType,
        tier: MemoryTier,
    ) -> Result<Self> {
        Self::new_with_depth(role, layer, None, rows, cols, dtype, tier)
    }

    pub(crate) fn new_rank3(
        role: WeightBlockRole,
        layer: Option<u32>,
        depth: usize,
        rows: usize,
        cols: usize,
        dtype: DType,
        tier: MemoryTier,
    ) -> Result<Self> {
        if depth == 0 {
            return Err(NervaError::InvalidArgument {
                reason: format!("weight block {} depth must be non-zero", role.as_str()),
            });
        }
        Self::new_with_depth(role, layer, Some(depth), rows, cols, dtype, tier)
    }

    fn new_with_depth(
        role: WeightBlockRole,
        layer: Option<u32>,
        depth: Option<usize>,
        rows: usize,
        cols: usize,
        dtype: DType,
        tier: MemoryTier,
    ) -> Result<Self> {
        if rows == 0 || cols == 0 {
            return Err(NervaError::InvalidArgument {
                reason: format!("weight block {} shape must be non-zero", role.as_str()),
            });
        }
        let elements = rows
            .checked_mul(cols)
            .and_then(|elements| match depth {
                Some(depth) => elements.checked_mul(depth),
                None => Some(elements),
            })
            .ok_or_else(|| NervaError::AllocationFailed {
                bytes: 0,
                reason: format!("weight block {} element count overflow", role.as_str()),
            })?;
        let bytes = dtype
            .packed_storage_bytes(elements)
            .map_err(|err| match err {
                NervaError::AllocationFailed { bytes, reason } => NervaError::AllocationFailed {
                    bytes,
                    reason: format!("weight block {} {reason}", role.as_str()),
                },
                other => other,
            })?;
        Ok(Self {
            role,
            layer,
            rows,
            cols,
            depth,
            elements,
            bytes,
            dtype,
            tier,
        })
    }
}
